-- MySQL Script generated by MySQL Workbench
-- Wed Nov 28 21:35:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE_CREDITO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE_CREDITO` (
  `ID_Cliente` INT NOT NULL,
  `Cuenta_Bancaria` VARCHAR(45) NULL,
  `Nombre_cliente` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ENFERMEDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ENFERMEDAD` (
  `Nombre_enfermedad` VARCHAR(45) NOT NULL,
  `Sintomas` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre_enfermedad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FAMILIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FAMILIA` (
  `Nombre_Familia` VARCHAR(45) NOT NULL,
  `ENFERMEDAD_Nombre_enfermedad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre_Familia`),
  CONSTRAINT `fk_FAMILIA_ENFERMEDAD1`
    FOREIGN KEY (`ENFERMEDAD_Nombre_enfermedad`)
    REFERENCES `mydb`.`ENFERMEDAD` (`Nombre_enfermedad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_FAMILIA_ENFERMEDAD1_idx` ON `mydb`.`FAMILIA` (`ENFERMEDAD_Nombre_enfermedad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`MEDICAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MEDICAMENTO` (
  `ID_Medicamento` INT NOT NULL,
  `Nombre_Medicamento` VARCHAR(45) NULL,
  `Precio` INT NULL,
  `Tipo_medicamento` VARCHAR(45) NULL,
  `FAMILIA_Nombre_Familia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Medicamento`),
  CONSTRAINT `fk_MEDICAMENTO_FAMILIA`
    FOREIGN KEY (`FAMILIA_Nombre_Familia`)
    REFERENCES `mydb`.`FAMILIA` (`Nombre_Familia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_MEDICAMENTO_FAMILIA_idx` ON `mydb`.`MEDICAMENTO` (`FAMILIA_Nombre_Familia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`LABORATORIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LABORATORIO` (
  `ID_Laboratorio` INT NOT NULL,
  `Nombre_laboratorio` VARCHAR(45) NULL,
  `Nombre_responsable` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Fax` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Laboratorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMPRA_MEDICAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMPRA_MEDICAMENTO` (
  `MEDICAMENTO_ID_Medicamento` INT NOT NULL,
  `LABORATORIO_ID_Laboratorio` INT NOT NULL,
  CONSTRAINT `fk_COMPRA_MEDICAMENTO_MEDICAMENTO1`
    FOREIGN KEY (`MEDICAMENTO_ID_Medicamento`)
    REFERENCES `mydb`.`MEDICAMENTO` (`ID_Medicamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_COMPRA_MEDICAMENTO_LABORATORIO1`
    FOREIGN KEY (`LABORATORIO_ID_Laboratorio`)
    REFERENCES `mydb`.`LABORATORIO` (`ID_Laboratorio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_COMPRA_MEDICAMENTO_MEDICAMENTO1_idx` ON `mydb`.`COMPRA_MEDICAMENTO` (`MEDICAMENTO_ID_Medicamento` ASC) VISIBLE;

CREATE INDEX `fk_COMPRA_MEDICAMENTO_LABORATORIO1_idx` ON `mydb`.`COMPRA_MEDICAMENTO` (`LABORATORIO_ID_Laboratorio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMPRA` (
  `CLIENTE_CREDITO_ID_Cliente` INT NOT NULL,
  `MEDICAMENTO_ID_Medicamento` INT NOT NULL,
  `Fecha_compra` DATE NULL,
  PRIMARY KEY (`CLIENTE_CREDITO_ID_Cliente`, `MEDICAMENTO_ID_Medicamento`),
  CONSTRAINT `fk_COMPRA_CLIENTE_CREDITO1`
    FOREIGN KEY (`CLIENTE_CREDITO_ID_Cliente`)
    REFERENCES `mydb`.`CLIENTE_CREDITO` (`ID_Cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_COMPRA_MEDICAMENTO1`
    FOREIGN KEY (`MEDICAMENTO_ID_Medicamento`)
    REFERENCES `mydb`.`MEDICAMENTO` (`ID_Medicamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_COMPRA_MEDICAMENTO1_idx` ON `mydb`.`COMPRA` (`MEDICAMENTO_ID_Medicamento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`VENTA_MEDICAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENTA_MEDICAMENTO` (
  `COMPRA_CLIENTE_CREDITO_ID_Cliente` INT NOT NULL,
  `COMPRA_MEDICAMENTO_ID_Medicamento` INT NOT NULL,
  `Unidades` VARCHAR(45) NULL,
  PRIMARY KEY (`COMPRA_CLIENTE_CREDITO_ID_Cliente`, `COMPRA_MEDICAMENTO_ID_Medicamento`),
  CONSTRAINT `fk_VENTA_MEDICAMENTO_COMPRA1`
    FOREIGN KEY (`COMPRA_CLIENTE_CREDITO_ID_Cliente` , `COMPRA_MEDICAMENTO_ID_Medicamento`)
    REFERENCES `mydb`.`COMPRA` (`CLIENTE_CREDITO_ID_Cliente` , `MEDICAMENTO_ID_Medicamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
