# Acceso al sistema psql: sudo -i -u postgres
# Acceso a la db farmacia: psql farmacia
# Mostrar tablas: \dt
# Mostrar atributos y características de una tabla: \d ‘nombretabla’

CREATE TABLE IF NOT EXISTS CLIENTE_CREDITO (
  ID_Cliente INT NOT NULL,
  Cuenta_Bancaria VARCHAR(45) NULL,
  Nombre_cliente VARCHAR(45) NULL,
  PRIMARY KEY (ID_Cliente));

CREATE TABLE IF NOT EXISTS ENFERMEDAD (
  Nombre_enfermedad VARCHAR(45) NOT NULL,
  Sintomas VARCHAR(45) NULL,
  PRIMARY KEY (Nombre_enfermedad));


CREATE TABLE IF NOT EXISTS FAMILIA (
  Nombre_Familia VARCHAR(45) NOT NULL,
  ENFERMEDAD_Nombre_enfermedad VARCHAR(45) NOT NULL,
  PRIMARY KEY (Nombre_Familia),
  CONSTRAINT fk_FAMILIA_ENFERMEDAD1
    FOREIGN KEY (ENFERMEDAD_Nombre_enfermedad)
    REFERENCES ENFERMEDAD (Nombre_enfermedad)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_FAMILIA_ENFERMEDAD1_idx ON FAMILIA (ENFERMEDAD_Nombre_enfermedad ASC);


CREATE TABLE IF NOT EXISTS MEDICAMENTO (
  ID_Medicamento INT NOT NULL,
  Nombre_Medicamento VARCHAR(45) NULL,
  Precio INT NULL,
  Tipo_medicamento VARCHAR(45) NULL,
  FAMILIA_Nombre_Familia VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID_Medicamento),
  CONSTRAINT fk_MEDICAMENTO_FAMILIA
    FOREIGN KEY (FAMILIA_Nombre_Familia)
    REFERENCES FAMILIA (Nombre_Familia)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_MEDICAMENTO_FAMILIA_idx ON MEDICAMENTO (FAMILIA_Nombre_Familia ASC);


CREATE TABLE IF NOT EXISTS LABORATORIO (
  ID_Laboratorio INT NOT NULL,
  Nombre_laboratorio VARCHAR(45) NULL,
  Nombre_responsable VARCHAR(45) NULL,
  Telefono VARCHAR(45) NULL,
  Fax VARCHAR(45) NULL,
  Direccion VARCHAR(45) NULL,
  PRIMARY KEY (ID_Laboratorio));


CREATE TABLE IF NOT EXISTS COMPRA_MEDICAMENTO (
  MEDICAMENTO_ID_Medicamento INT NOT NULL,
  LABORATORIO_ID_Laboratorio INT NOT NULL,
  CONSTRAINT fk_COMPRA_MEDICAMENTO_MEDICAMENTO1
    FOREIGN KEY (MEDICAMENTO_ID_Medicamento)
    REFERENCES MEDICAMENTO (ID_Medicamento)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_COMPRA_MEDICAMENTO_LABORATORIO1
    FOREIGN KEY (LABORATORIO_ID_Laboratorio)
    REFERENCES LABORATORIO (ID_Laboratorio)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_COMPRA_MEDICAMENTO_MEDICAMENTO1_idx ON COMPRA_MEDICAMENTO (MEDICAMENTO_ID_Medicamento ASC);

CREATE INDEX fk_COMPRA_MEDICAMENTO_LABORATORIO1_idx ON COMPRA_MEDICAMENTO (LABORATORIO_ID_Laboratorio ASC);



CREATE TABLE IF NOT EXISTS COMPRA (
  CLIENTE_CREDITO_ID_Cliente INT NOT NULL,
  MEDICAMENTO_ID_Medicamento INT NOT NULL,
  Fecha_compra DATE NULL,
  PRIMARY KEY (CLIENTE_CREDITO_ID_Cliente, MEDICAMENTO_ID_Medicamento),
  CONSTRAINT fk_COMPRA_CLIENTE_CREDITO1
    FOREIGN KEY (CLIENTE_CREDITO_ID_Cliente)
    REFERENCES CLIENTE_CREDITO (ID_Cliente)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_COMPRA_MEDICAMENTO1
    FOREIGN KEY (MEDICAMENTO_ID_Medicamento)
    REFERENCES MEDICAMENTO (ID_Medicamento)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE INDEX fk_COMPRA_MEDICAMENTO1_idx ON COMPRA (MEDICAMENTO_ID_Medicamento ASC);


CREATE TABLE IF NOT EXISTS VENTA_MEDICAMENTO (
  COMPRA_CLIENTE_CREDITO_ID_Cliente INT NOT NULL,
  COMPRA_MEDICAMENTO_ID_Medicamento INT NOT NULL,
  Unidades VARCHAR(45) NULL,
  PRIMARY KEY (COMPRA_CLIENTE_CREDITO_ID_Cliente, COMPRA_MEDICAMENTO_ID_Medicamento),
  CONSTRAINT fk_VENTA_MEDICAMENTO_COMPRA1
    FOREIGN KEY (COMPRA_CLIENTE_CREDITO_ID_Cliente , COMPRA_MEDICAMENTO_ID_Medicamento)
    REFERENCES COMPRA (CLIENTE_CREDITO_ID_Cliente , MEDICAMENTO_ID_Medicamento)
    ON DELETE CASCADE
    ON UPDATE CASCADE);




