CREATE TABLE IF NOT EXISTS EMPLEADO (
  ID_trabajador INT NOT NULL,
  Nombre VARCHAR(45) NULL,
  Apellidos VARCHAR(45) NULL,
  Formación VARCHAR(45) NULL,
  Tipo_contrato VARCHAR(45) NULL,
  PRIMARY KEY (ID_trabajador));

CREATE TABLE IF NOT EXISTS TELEFONO_TRABAJADOR (
  Telefono_trabajador VARCHAR(45) NOT NULL,
  EMPLEADO_ID_trabajador INT NOT NULL,
  PRIMARY KEY (Telefono_trabajador, EMPLEADO_ID_trabajador),
  CONSTRAINT fk_TELEFONO_TRABAJADOR_EMPLEADO
    FOREIGN KEY (EMPLEADO_ID_trabajador)
    REFERENCES EMPLEADO (ID_trabajador)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_TELEFONO_TRABAJADOR_EMPLEADO_idx ON TELEFONO_TRABAJADOR (EMPLEADO_ID_trabajador ASC) ;

CREATE TABLE IF NOT EXISTS CHEF (
  EMPLEADO_ID_trabajador INT NOT NULL,
  PRIMARY KEY (EMPLEADO_ID_trabajador),
  CONSTRAINT fk_CHEF_EMPLEADO1
    FOREIGN KEY (EMPLEADO_ID_trabajador)
    REFERENCES EMPLEADO (ID_trabajador)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS ENCARGADO (
  EMPLEADO_ID_trabajador INT NOT NULL,
  PRIMARY KEY (EMPLEADO_ID_trabajador),
  CONSTRAINT fk_ENCARGADO_EMPLEADO1
    FOREIGN KEY (EMPLEADO_ID_trabajador)
    REFERENCES EMPLEADO (ID_trabajador)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS AYUDANTE (
  EMPLEADO_ID_trabajador INT NOT NULL,
  PRIMARY KEY (EMPLEADO_ID_trabajador),
  CONSTRAINT fk_AYUDANTE_EMPLEADO1
    FOREIGN KEY (EMPLEADO_ID_trabajador)
    REFERENCES EMPLEADO (ID_trabajador)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS DIRIGE (
  CHEF_EMPLEADO_ID_trabajador INT NOT NULL,
  ENCARGADO_EMPLEADO_ID_trabajador INT NOT NULL,
  PRIMARY KEY (CHEF_EMPLEADO_ID_trabajador),
  CONSTRAINT fk_DIRIGE_CHEF1
    FOREIGN KEY (CHEF_EMPLEADO_ID_trabajador)
    REFERENCES CHEF (EMPLEADO_ID_trabajador)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_DIRIGE_ENCARGADO1
    FOREIGN KEY (ENCARGADO_EMPLEADO_ID_trabajador)
    REFERENCES ENCARGADO (EMPLEADO_ID_trabajador)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_DIRIGE_ENCARGADO1_idx ON DIRIGE (ENCARGADO_EMPLEADO_ID_trabajador ASC) ;

CREATE TABLE IF NOT EXISTS COORDINA (
  ENCARGADO_EMPLEADO_ID_trabajador INT NOT NULL,
  AYUDANTE_EMPLEADO_ID_trabajador INT NOT NULL,
  PRIMARY KEY (ENCARGADO_EMPLEADO_ID_trabajador),
  CONSTRAINT fk_COORDINA_ENCARGADO1
    FOREIGN KEY (ENCARGADO_EMPLEADO_ID_trabajador)
    REFERENCES ENCARGADO (EMPLEADO_ID_trabajador)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_COORDINA_AYUDANTE1
    FOREIGN KEY (AYUDANTE_EMPLEADO_ID_trabajador)
    REFERENCES AYUDANTE (EMPLEADO_ID_trabajador)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_COORDINA_AYUDANTE1_idx ON COORDINA (AYUDANTE_EMPLEADO_ID_trabajador ASC) ;


CREATE TABLE IF NOT EXISTS NOMINA (
  ID_nomina INT NOT NULL,
  Salario_base INT NULL,
  Penalización INT NULL,
  Suelto_total INT NULL,
  PRIMARY KEY (ID_nomina));


CREATE TABLE IF NOT EXISTS COBRA (
  EMPLEADO_ID_trabajador INT NOT NULL,
  NOMINA_ID_nomina INT NOT NULL,
  PRIMARY KEY (EMPLEADO_ID_trabajador, NOMINA_ID_nomina),
  CONSTRAINT fk_COBRA_EMPLEADO1
    FOREIGN KEY (EMPLEADO_ID_trabajador)
    REFERENCES EMPLEADO (ID_trabajador)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_COBRA_NOMINA1
    FOREIGN KEY (NOMINA_ID_nomina)
    REFERENCES NOMINA (ID_nomina)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_COBRA_NOMINA1_idx ON COBRA (NOMINA_ID_nomina ASC) ;

CREATE TABLE IF NOT EXISTS TAREA (
  ID_tarea INT NOT NULL,
  Nombre_tarea VARCHAR(45) NULL,
  PRIMARY KEY (ID_tarea));

CREATE TABLE IF NOT EXISTS REALIZA (
  EMPLEADO_ID_trabajador INT NOT NULL,
  TAREA_ID_tarea INT NOT NULL,
  Tiempo_empleado INT NULL,
  PRIMARY KEY (EMPLEADO_ID_trabajador, TAREA_ID_tarea),
  CONSTRAINT fk_REALIZA_EMPLEADO1
    FOREIGN KEY (EMPLEADO_ID_trabajador)
    REFERENCES EMPLEADO (ID_trabajador)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_REALIZA_TAREA1
    FOREIGN KEY (TAREA_ID_tarea)
    REFERENCES TAREA (ID_tarea)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_REALIZA_TAREA1_idx ON REALIZA (TAREA_ID_tarea ASC) ;

CREATE TABLE IF NOT EXISTS SE_FORMA (
  EMPLEADO_ID_trabajador INT NOT NULL,
  TAREA_ID_tarea INT NOT NULL,
  Fecha DATE NULL,
  Calificacion VARCHAR(45) NULL,
  Nombre_curso VARCHAR(45) NULL,
  PRIMARY KEY (EMPLEADO_ID_trabajador, TAREA_ID_tarea),
  CONSTRAINT fk_SE_FORMA_EMPLEADO1
    FOREIGN KEY (EMPLEADO_ID_trabajador)
    REFERENCES EMPLEADO (ID_trabajador)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_SE_FORMA_TAREA1
    FOREIGN KEY (TAREA_ID_tarea)
    REFERENCES TAREA (ID_tarea)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_SE_FORMA_TAREA1_idx ON SE_FORMA (TAREA_ID_tarea ASC) ;

CREATE TABLE IF NOT EXISTS RESTAURANTE (
  ID_rest INT NOT NULL,
  Nombre_rest VARCHAR(45) NULL,
  EMPLEADO_ID_trabajador INT NOT NULL,
  PRIMARY KEY (ID_rest),
  CONSTRAINT fk_RESTAURANTE_EMPLEADO1
    FOREIGN KEY (EMPLEADO_ID_trabajador)
    REFERENCES EMPLEADO (ID_trabajador)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_RESTAURANTE_EMPLEADO1_idx ON RESTAURANTE (EMPLEADO_ID_trabajador ASC) ;

CREATE TABLE IF NOT EXISTS CLIENTE (
  ID_cliente INT NOT NULL,
  Nombre VARCHAR(45) NULL,
  Apellidos VARCHAR(45) NULL,
  Fecha_nacimiento DATE NULL,
  PRIMARY KEY (ID_cliente));

CREATE TABLE IF NOT EXISTS TIENE (
  RESTAURANTE_ID_rest INT NOT NULL,
  CLIENTE_ID_cliente INT NOT NULL,
  PRIMARY KEY (RESTAURANTE_ID_rest, CLIENTE_ID_cliente),
  CONSTRAINT fk_TIENE_RESTAURANTE1
    FOREIGN KEY (RESTAURANTE_ID_rest)
    REFERENCES RESTAURANTE (ID_rest)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_TIENE_CLIENTE1
    FOREIGN KEY (CLIENTE_ID_cliente)
    REFERENCES CLIENTE (ID_cliente)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_TIENE_CLIENTE1_idx ON TIENE (CLIENTE_ID_cliente ASC) ;

CREATE TABLE IF NOT EXISTS TELEFONO_CLIENTE (
  Telefono_cliente INT NOT NULL,
  CLIENTE_ID_cliente INT NOT NULL,
  PRIMARY KEY (Telefono_cliente, CLIENTE_ID_cliente),
  CONSTRAINT fk_TELEFONO_CLIENTE_CLIENTE1
    FOREIGN KEY (CLIENTE_ID_cliente)
    REFERENCES CLIENTE (ID_cliente)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_TELEFONO_CLIENTE_CLIENTE1_idx ON TELEFONO_CLIENTE (CLIENTE_ID_cliente ASC) ;

CREATE TABLE IF NOT EXISTS TRABAJA (
  RESTAURANTE_ID_rest INT NOT NULL,
  EMPLEADO_ID_trabajador INT NOT NULL,
  PRIMARY KEY (RESTAURANTE_ID_rest, EMPLEADO_ID_trabajador),
  CONSTRAINT fk_TRABAJA_RESTAURANTE1
    FOREIGN KEY (RESTAURANTE_ID_rest)
    REFERENCES RESTAURANTE (ID_rest)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_TRABAJA_EMPLEADO1
    FOREIGN KEY (EMPLEADO_ID_trabajador)
    REFERENCES EMPLEADO (ID_trabajador)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_TRABAJA_EMPLEADO1_idx ON TRABAJA (EMPLEADO_ID_trabajador ASC) ;

CREATE TABLE IF NOT EXISTS INSPECCION (
  ID_inspecc INT NOT NULL,
  Nombre_inspector VARCHAR(45) NULL,
  EMPLEADO_ID_trabajador INT NOT NULL,
  PRIMARY KEY (ID_inspecc, EMPLEADO_ID_trabajador),
  CONSTRAINT fk_INSPECCION_EMPLEADO1
    FOREIGN KEY (EMPLEADO_ID_trabajador)
    REFERENCES EMPLEADO (ID_trabajador)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_INSPECCION_EMPLEADO1_idx ON INSPECCION (EMPLEADO_ID_trabajador ASC) ;

CREATE TABLE IF NOT EXISTS SE_SOMETE (
  RESTAURANTE_ID_rest INT NOT NULL,
  INSPECCION_ID_inspecc INT NOT NULL,
 INSPECCION_EMPLEADO_ID_trabajador INT NOT NULL,
  PRIMARY KEY (RESTAURANTE_ID_rest, INSPECCION_ID_inspecc, INSPECCION_EMPLEADO_ID_trabajador),
  CONSTRAINT fk_SE_SOMETE_RESTAURANTE1
    FOREIGN KEY (RESTAURANTE_ID_rest)
    REFERENCES RESTAURANTE (ID_rest)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
 CONSTRAINT fk_SE_SOMETE_INSPECCION1
    FOREIGN KEY (INSPECCION_ID_inspecc,INSPECCION_EMPLEADO_ID_trabajador)
    REFERENCES INSPECCION (ID_inspecc, EMPLEADO_ID_trabajador)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_SE_SOMETE_INSPECCION1_idx ON SE_SOMETE (INSPECCION_ID_inspecc ASC) ;

CREATE TABLE IF NOT EXISTS PRENDA (
  ID_prenda INT NOT NULL,
  EMPLEADO_ID_trabajador INT NOT NULL,
  Nombre_prenda VARCHAR(45) NULL,
  Durabilidad VARCHAR(45) NULL,
  PRIMARY KEY (ID_prenda, EMPLEADO_ID_trabajador),
  CONSTRAINT fk_PRENDA_EMPLEADO1
    FOREIGN KEY (EMPLEADO_ID_trabajador)
    REFERENCES EMPLEADO (ID_trabajador)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_PRENDA_EMPLEADO1_idx ON PRENDA (EMPLEADO_ID_trabajador ASC) ;

CREATE TABLE IF NOT EXISTS HABITUAL (
  CLIENTE_ID_cliente INT NOT NULL,
  PRIMARY KEY (CLIENTE_ID_cliente),
  CONSTRAINT fk_HABITUAL_CLIENTE1
    FOREIGN KEY (CLIENTE_ID_cliente)
    REFERENCES CLIENTE (ID_cliente)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS VIP (
  CLIENTE_ID_cliente INT NOT NULL,
  PRIMARY KEY (CLIENTE_ID_cliente),
  CONSTRAINT fk_VIP_CLIENTE1
    FOREIGN KEY (CLIENTE_ID_cliente)
    REFERENCES CLIENTE (ID_cliente)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS MESA (
  N_mesa INT NOT NULL,
  Plazas INT NULL,
  PRIMARY KEY (N_mesa));

CREATE TABLE IF NOT EXISTS RESERVA (
  CLIENTE_ID_cliente INT NOT NULL,
  MESA_N_mesa INT NOT NULL,
  Fecha DATE NOT NULL,
  PRIMARY KEY (CLIENTE_ID_cliente, MESA_N_mesa, Fecha),
  CONSTRAINT fk_RESERVA_CLIENTE1
    FOREIGN KEY (CLIENTE_ID_cliente)
    REFERENCES CLIENTE (ID_cliente)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_RESERVA_MESA1
    FOREIGN KEY (MESA_N_mesa)
    REFERENCES MESA (N_mesa)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_RESERVA_MESA1_idx ON RESERVA (MESA_N_mesa ASC) ;

CREATE TABLE IF NOT EXISTS PREFIERE (
  VIP_CLIENTE_ID_cliente INT NOT NULL,
  MESA_N_mesa INT NOT NULL,
  PRIMARY KEY (VIP_CLIENTE_ID_cliente, MESA_N_mesa),
  CONSTRAINT fk_PREFIERE_VIP1
    FOREIGN KEY (VIP_CLIENTE_ID_cliente)
    REFERENCES VIP (CLIENTE_ID_cliente)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_PREFIERE_MESA1
    FOREIGN KEY (MESA_N_mesa)
    REFERENCES MESA (N_mesa)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_PREFIERE_MESA1_idx ON PREFIERE (MESA_N_mesa ASC) ;

CREATE TABLE IF NOT EXISTS PEDIDO (
  ID_pedido INT NOT NULL,
  CLIENTE_ID_cliente INT NOT NULL,
  Cod_factura INT NULL,
  Fecha DATE NULL,
  Metodo_pago VARCHAR(45) NULL,
  Importe INT NULL,
  PRIMARY KEY (ID_pedido),
  CONSTRAINT fk_PEDIDO_CLIENTE1
    FOREIGN KEY (CLIENTE_ID_cliente)
    REFERENCES CLIENTE (ID_cliente)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_PEDIDO_CLIENTE1_idx ON PEDIDO (CLIENTE_ID_cliente ASC) ;

CREATE TABLE IF NOT EXISTS PLATO (
  Nombre_plato VARCHAR(45) NOT NULL,
  Precio INT NULL,
  PRIMARY KEY (Nombre_plato));

CREATE TABLE IF NOT EXISTS ALERGENOS (
  PLATO_Nombre_plato VARCHAR(45) NOT NULL,
  Alergeno VARCHAR(45) NULL,
  PRIMARY KEY (PLATO_Nombre_plato),
  CONSTRAINT fk_ALERGENOS_PLATO1
    FOREIGN KEY (PLATO_Nombre_plato)
    REFERENCES PLATO (Nombre_plato)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS INGREDIENTE (
  Nombre_ingrediente VARCHAR(45) NOT NULL,
  Precio INT NULL,
  Stock INT NULL,
  PRIMARY KEY (Nombre_ingrediente));

CREATE TABLE IF NOT EXISTS COMPUESTO (
  PLATO_Nombre_plato VARCHAR(45) NOT NULL,
  INGREDIENTE_Nombre_ingrediente VARCHAR(45) NOT NULL,
  Cantidad INT NULL,
  PRIMARY KEY (PLATO_Nombre_plato, INGREDIENTE_Nombre_ingrediente),
  CONSTRAINT fk_COMPUESTO_PLATO1
    FOREIGN KEY (PLATO_Nombre_plato)
    REFERENCES PLATO (Nombre_plato)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_COMPUESTO_INGREDIENTE1
    FOREIGN KEY (INGREDIENTE_Nombre_ingrediente)
    REFERENCES INGREDIENTE (Nombre_ingrediente)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_COMPUESTO_INGREDIENTE1_idx ON COMPUESTO (INGREDIENTE_Nombre_ingrediente ASC) ;

CREATE TABLE IF NOT EXISTS FORMADA (
  PEDIDO_ID_pedido INT NOT NULL,
  PLATO_Nombre_plato VARCHAR(45) NOT NULL,
  Numero_platos INT NULL,
  PRIMARY KEY (PEDIDO_ID_pedido, PLATO_Nombre_plato),
  CONSTRAINT fk_FORMADA_PEDIDO1
    FOREIGN KEY (PEDIDO_ID_pedido)
    REFERENCES PEDIDO (ID_pedido)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_FORMADA_PLATO1
    FOREIGN KEY (PLATO_Nombre_plato)
    REFERENCES PLATO (Nombre_plato)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_FORMADA_PLATO1_idx ON FORMADA (PLATO_Nombre_plato ASC) ;

