-- MySQL Script generated by MySQL Workbench
-- Thu Jan 10 12:54:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS mydb DEFAULT CHARACTER SET utf8 ;
USE mydb ;

-- -----------------------------------------------------
-- Table mydb.VIVERO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.VIVERO (
  Coordenadas INT NOT NULL,
  localidad VARCHAR(45) NULL,
  PRIMARY KEY (Coordenadas))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.ZONA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.ZONA (
  Nombre VARCHAR(45) NOT NULL,
  Producto VARCHAR(45) NULL,
  VIVERO_Coordenadas INT NOT NULL,
  PRIMARY KEY (Nombre, VIVERO_Coordenadas),
  CONSTRAINT fk_ZONA_VIVERO1
    FOREIGN KEY (VIVERO_Coordenadas)
    REFERENCES mydb.VIVERO (Coordenadas)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_ZONA_VIVERO1_idx ON mydb.ZONA (VIVERO_Coordenadas ASC) VISIBLE;


-- -----------------------------------------------------
-- Table mydb.PRODUCTO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.PRODUCTO (
  Codigo INT NOT NULL,
  Stock TINYINT(4) NULL,
  PRIMARY KEY (Codigo))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.CLIENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.CLIENTE (
  dni INT NOT NULL,
  Bonificacion TINYINT(4) NULL,
  Total TINYINT(4) NULL,
  PRIMARY KEY (dni))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.EMPLEADO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.EMPLEADO (
  dni INT NOT NULL,
  Sueldo TINYINT(4) NULL,
  CSS TINYINT(4) NULL,
  Coordenadas TINYINT(4) NULL,
  Nombre VARCHAR(45) NULL,
  PRIMARY KEY (dni),
  CONSTRAINT fk_EMPLEADO_1
    FOREIGN KEY (Nombre)
    REFERENCES mydb.ZONA (Nombre)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_EMPLEADO_1_idx ON mydb.EMPLEADO (Coordenadas ASC, Nombre ASC) VISIBLE;


-- -----------------------------------------------------
-- Table mydb.PROD_EMP_CLIENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.PROD_EMP_CLIENTE (
  dni_e INT NOT NULL,
  Codigo INT NOT NULL,
  fecha TINYINT(4) NOT NULL,
  Cantidad VARCHAR(45) NULL,
  dni_c INT NOT NULL,
  PRIMARY KEY (dni_e, Codigo, fecha, dni_c),
  CONSTRAINT fk_PROD_EMP_CLIENTE_1
    FOREIGN KEY (Codigo)
    REFERENCES mydb.PRODUCTO (Codigo)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PROD_EMP_CLIENTE_2
    FOREIGN KEY (dni_c)
    REFERENCES mydb.CLIENTE (dni)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PROD_EMP_CLIENTE_3
    FOREIGN KEY (dni_e)
    REFERENCES mydb.EMPLEADO (dni)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_PROD_EMP_CLIENTE_1_idx ON mydb.PROD_EMP_CLIENTE (Codigo ASC) VISIBLE;
CREATE INDEX fk_PROD_EMP_CLIENTE_2_idx ON mydb.PROD_EMP_CLIENTE (dni_c ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
