CREATE OR REPLACE FUNCTION function()
RETURNS TRIGGER AS $ACTUALIZAR_LABORATORIO$
BEGIN
RAISE EXCEPTION 'No se permite la actualización de los datos de la tabla laboratorio';
END;
$ACTUALIZAR_LABORATORIO$ language plpgsql;


CREATE TRIGGER ACTUALIZAR_LABORATORIO 
BEFORE UPDATE ON LABORATORIO
FOR EACH ROW
EXECUTE PROCEDURE function();
