
CREATE OR REPLACE FUNCTION crear_prenda()
RETURNS TRIGGER AS $CREAR_PRENDA$
DECLARE 
v_id INTEGER;
BEGIN
SELECT MAX(id_prenda) INTO v_id
FROM PRENDA; 
v_id:=v_id+1;

INSERT INTO PRENDA VALUES(v_id,NEW.id_trabajador,’rellenar’,0);

RETURN NEW;
END;
$CREAR_PRENDA$ language plpgsql;


CREATE TRIGGER CREAR_PRENDA
AFTER INSERT ON EMPLEADO
FOR EACH ROW
EXECUTE PROCEDURE crear_prenda();
